export type ParsedEnv = {
  nodeEnv: 'development' | 'test' | 'production';
  telegramBotToken: string;
  llmApiKey: string;
  llmBaseUrl: string;
  llmReplyModel: string;
  llmPlannerModel: string;
  llmReplyTemperature: number;
  llmReplyEnableThinking: boolean;
  llmTimeoutMs: number;
  llmMaxRetries: number;
  logLlmText: boolean;
  logLevel: 'debug' | 'info' | 'warn' | 'error';
  logColor: boolean;
  sqlitePath: string;
  answerContextLimit: number;
  summarizeContextLimit: number;
  decideContextLimit: number;
  replyMinTypingMs: number;
  replyMaxTypingMs: number;
  replyTypingRefreshMs: number;
  lookupEnabled: boolean;
  lookupProvider: 'tavily';
  tavilyApiKey: string | null;
  lookupTimeoutMs: number;
  lookupMaxQueries: number;
  lookupMaxResults: number;
  mediaAnalysisEnabled: boolean;
  ocrSpaceApiKey: string | null;
  readContextLimit: number;
  sttProvider: 'gladia';
  gladiaApiKey: string | null;
  visionProvider: 'cloudflare';
  cloudflareAiApiKey: string | null;
  cloudflareAccountId: string | null;
  mediaMaxFileBytes: number;
  mediaArtifactRetentionDays: number;
  messageRetentionDays: number;
  databaseCleanupIntervalHours: number;
  deployNotifyChatId: number;
};

export type AppEnv = ParsedEnv;
